{% set name = "msprime" %}
{% set version = "1.0.1" %}
{% set sha256 = "75bd228a961ec3f56b15e21a1671d4fa1c1056235f8e04ce1cb1f8ee61c88127" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - mspms=msprime.cli:mspms_main
    - msp=msprime.cli:msp_main
  # We use this to skip Python2 builds rather than specifying python3 >=3.7 below
  # as this broke windows builds.
  skip: true  # [py<37]

# Following the guidance here for building against numpy:
# https://conda-forge.org/docs/meta.html#building-against-numpy
# Not pinning GSL here because it is included in the conda-forge-pinning.
requirements:
  build:
    - {{ compiler('c') }}
  host:
    - setuptools
    - setuptools_scm
    - python
    - pip
    - numpy
    - gsl
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - gsl
    - tskit

test:
  imports:
    - msprime
  commands:
    - mspms --help
    - msp --help

about:
  home: http://pypi.python.org/pypi/msprime
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Population genetics simulator
  description: Simulate genealogical trees and genomic sequence data using population genetic models
  doc_url: http://tskit.dev/msprime/docs/stable
  dev_url: https://github.com/tskit-dev/msprime

extra:
  recipe-maintainers:
    - jeromekelleher
