{% set name = "msprime" %}
{% set version = "0.6.1" %}
{% set sha256 = "974c7dac8e30436fab6f1e19d2e0767ff20626893c49bbcc8e0d087ea54b6e3a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - mspms=msprime.cli:mspms_main
    - msp=msprime.cli:msp_main
  # We need C99 and the Windows compilers before py35 won't work.
  skip: True  # [win and py<35]

# Following the guidance here for building against numpy:
# https://conda-forge.org/docs/meta.html#building-against-numpy
# Not pinning GSL here because it is included in the conda-forge-pinning.
requirements:
  build:
    - {{ compiler('c') }}
  host:
    - setuptools
    - setuptools_scm
    - python
    - pip
    - numpy
    - gsl
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - gsl
    - six
    - h5py
    - svgwrite
    - jsonschema

test:
  imports:
    - msprime
  commands:
    - mspms --help
    - msp --help

about:
  home: http://pypi.python.org/pypi/msprime
  license: GPL-3.0
  license_family: GPL
  license_file: 'LICENSE'
  summary: A fast and accurate coalescent simulator.
  description: Coalescent simulator and library for working with succinct tree sequences.
  doc_url: 'http://msprime.readthedocs.io/en/stable'
  dev_url: 'https://github.com/jeromekelleher/msprime'

extra:
  recipe-maintainers:
    - jeromekelleher
