travis:
  secure:
    BINSTAR_TOKEN: MqYq2DuA3gGpIV2k0CSlrdXWgNeQB1ej3ECR6+X/+Rr4PZ07cpVB2IXp2Dd3dRNBVQ/5TZt632mPTG2rkYiM1uMKOqFNNGbnWQRVF5JHccUzAEpBwPPUBN56PC+x2mX+FzPZP6p+nf/cTOsdmHuB69buApGuEj6RE+COqSBgi589306bzw+XJl4Ty7x2am3dQneiRLF77AIi5nRUzyQx3LAXIlv9X35rSvu7sEWowM0gIkXBwEYNS4upTw6T66DUeXnDfAfgHHR8QRb8Wmm0M61+GvD2ARar3mXLQk2f4BNp/hK3OKwizu3hBhljPYKwuRT6RCKgIgZFpivqN1AEoy1+25vMXAOq7fr67pTvgwy5rN6xCLT5hvuTcF+sT0DLsd51Zywc33KT0w1VDbqWAycTWsc/WOlzgPHkw2agQ5z8fV6KLjJYg9ntpncTp8B37cd2hGL1aLeUn+jGXI1O4l6gfuQI7UP2dw7zF7mhCkmej0JB94FVi7ccG+07KekhJ0AMJ3vV65TO+5rcIyNNW5An4TJdwmb8HhfTjo9jKCEMDwUiIiyTOIu67D02YyPDCmSirl/kispGsz6Wej7UpItTIUsZGfXTrEMWiLAcp7xe7E7oOG21Rcas8QUqAjUD+1izvTGXGBFJwRPUfMxU+qx0ulNE3JuuVdAPmncXxHg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
